# Generated by Django 5.0.7 on 2025-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0002_datosensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosensor',
            name='distancia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datosensor',
            name='humedad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datosensor',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
